### PR TITLE
Add shiny official artwork Teal Mask pokemon

### PR DESCRIPTION
**Pull request by CloudDCrow**
Images from TonOfDirt726 on DeviantArt

### CODE REVIEW

**Comment by CloudDCrow** [comment]
I didn't know how to handle Ogerpon, since its official artwork is the same when it's shiny. Also, there don't seem to be any official images of it wearing different masks...

**Comment by Naramsim** [comment]
Hi! Could you ask the designer over at DeviantArt if we can use his images?

**Comment by CloudDCrow** [comment]
> Hi! Could you ask the designer over at DeviantArt if we can use his images?

Yes, we can. However, if they would get credited (not required but appreciated), they would prefer to be credited from imgbb and not deviantart. So https://tonofdirt726.imgbb.com/

**Comment by Naramsim** [comment]
Another question, are we sure we want to add these unofficial sprites to the `official-sprites` category 🤣

**Comment by Naramsim** [comment]
I'd use these ones: https://www.pokemon.com/us/pokedex It seems they are available. if you search for `1009` and `1010` they are there.

The others not yet unfortunately

**Comment by CloudDCrow** [comment]
These are all official, it's just that the Pokemon company is too lazy to update their website 🤣 Here they are in the official Scarlet/Violet website https://scarletviolet.pokemon.com/en-us/pokemon/

**Comment by CloudDCrow** [comment]
The other 4 were revealed on twitter... Again, they are just too lazy to upload them to the official pokedex site idk.
The legendary trio: https://twitter.com/Pokemon/status/1702427043223437325
Terapagos : https://twitter.com/Pokemon/status/1647948029805182976?lang=en

**Comment by Naramsim** [comment]
Ok! Then we don't need to credit anyone if they are official!

**Review by Naramsim — APPROVED** [review]

**Pull request merged**
