### PR TITLE
Add Teal Mask sprites

### PR DESCRIPTION
**Pull request by declantyson**
Added front_default sprites for Teal Mask Pokémon in pixelated style of B/W
 courtesy of  [KingOfThe-X-Roads](https://www.deviantart.com/kingofthe-x-roads) in line with other Gen 9 sprites

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, they seem low resolution. What's the dimension?

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Ok, I checked and they are 90x90. Thanks!

**Comment by RyanLivingston** [comment]
Hello, 

This may not be the appropriate place to ask this. I run PokeDoku.com and we use this repository for ingesting and displaying sprites. Do you guys normally follow any protocol when gathering sprites to submit a PR. We would like to contribute to the repository by uploading sprites that we find are missing.

Ryan

**Comment by Naramsim** [comment]
> Hello, 
> 
> This may not be the appropriate place to ask this. I run PokeDoku.com and we use this repository for ingesting and displaying sprites. Do you guys normally follow any protocol when gathering sprites to submit a PR. We would like to contribute to the repository by uploading sprites that we find are missing.
> 
> Ryan

Hi Ryan! We don't really follow any protocol. We are looking for sprites with the same dimensions. If you d like to submit some new sprites feel free to open pull requests and I'll try to review them.

**Pull request merged**
