### PR TITLE
Added missing official artwork images:

### PR DESCRIPTION
**Pull request by WOTstorm**
Added missing official artwork images:
#10080 pikachu-rock-star
#10081 pikachu-belle
#10082 pikachu-pop-star
#10083 pikachu-phd
#10084 pikachu-libre
#10085 pikachu-cosplay
#10094 pikachu-original-cap
#10095 pikachu-hoenn-cap
#10096 pikachu-sinnoh-cap
#10097 pikachu-unova-cap
#10098 pikachu-kalos-cap
#10099 pikachu-alola-cap
#10117 greninja-ash
#10148 pikachu-partner-cap
#10179 eiscue-noice

### CODE REVIEW

**Comment by Naramsim** [comment]
Cool! Where did you find them?

**Comment by WOTstorm** [comment]
Hi, I found some of them on the official Pokémon website. Others I found on bulbapedia.

**Comment by Naramsim** [comment]
Could you please remove Eiscue-noice? That image isn't the official one, I believe. The neck looks very pixellated

**Comment by WOTstorm** [comment]
As far as I can tell this is the official artwork.
* https://zukan.pokemon.co.jp/
* https://zukan.pokemon.co.jp/detail/875-1

I updated the image for a slightly better quality.

**Comment by Naramsim** [comment]
Thanks a lot!

**Pull request merged**
