### PR TITLE
Add missing official artworks

### PR DESCRIPTION
**Pull request by aabeborn**
Hi! relating to this [issue](https://github.com/PokeAPI/pokeapi/issues/550) I have put some of the missing artworks.

I have made some assumptions like:
- Totem pokemons have the same artwork of the normal one
- Pumpkaboom and gourgeist, which have different size variants ahave the same artwork
- Eternatus Eternmax form has no artwork in pokemon.com website I have used the one used in bulbapedia

If you want I have also the greninja different forms and minior core forms ready, there aren't taken as Eternatus from the official website

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @aabeborn, thanks for the contribution. Did you scrape the artworks from pokemon.com? If so, please only use pokemon.com and remove the ones taken from other websites such as Bulbapedia.

**Comment by aabeborn** [comment]
I used pokemon.com for almost all the artworks only few of them has been taught from bulbapedia because not listen in pokemon.com

**Comment by Naramsim** [comment]
Then, can you remove those taken from other sources from this PR?

**Comment by aabeborn** [comment]
Sure no problem!

**Comment by aabeborn** [comment]
@Naramsim  done it!

**Comment by Naramsim** [comment]
Thanks a lot!

**Pull request merged**
