### PR TITLE
Add & fix various incorrect or missing sprites

### PR DESCRIPTION
**Pull request by rayusagi**
- added missing Pikachu Word Cap front/back sprites
- added missing female Eevee front/back/shiny sprites
- added missing Spiky-Eared Pichu front sprite
- changed Torchic female front sprites (default and shiny)
  The existing ones were not consistent with the general B/W style. The back sprites were already in that B/W style but the front ones were not. Since there is no visible difference between the two on the frontside (the actual difference is an extra pixel on the rear of the male), the same sprites as the male were used.

- changed Buizel and Floatzel female front sprites (default and shiny)
  The exact same reason as Torchic. And just like Torchic, no difference is visible on the frontside so the same sprites as the male were used.

- added missing Meowstic female front/back/shiny sprites
  Female Meowstic has a distinct pokémon ID in the API (10025) that didn't have sprites for the default backside and both shiny sides.

- added missing Indeedee female front/back/shiny sprites
  Female Indeedee has a distinct pokémon ID in the API (10186) that didn't have sprites for the default backside and both shiny sides.

### CODE REVIEW

**Review by Naramsim — APPROVED** [review]

**Comment by rayusagi** [comment]
Thanks! 
However, for the new sprites I cannot witness the change in the API.
E.g. [Pikachu World Cap](https://pokeapi.co/api/v2/pokemon/10160) :
```json
"sprites": {
        "back_default": null,
        "back_female": null,
        "back_shiny": null,
        "back_shiny_female": null,
        "front_default": null,
        "front_female": null,
        "front_shiny": null,
        "front_shiny_female": null,
...
}
```
What needs to be done for it to appear there?
When I worked in local, after I had rebuild the database. Is it not what has been done here https://github.com/PokeAPI/pokeapi/pull/1158#issuecomment-2464137991 recently?
I can see [here](https://github.com/PokeAPI/api-data/blob/ee08e09badf23846f2603162c330a60ef37f5bc3/data/api/v2/pokemon/10160/index.json) that it has actually been edited like expected.
What am I missing?

**Comment by Naramsim** [comment]
Caching, tomorrow I'll purge

**Comment by Naramsim** [comment]
Ok, can you try now?

**Comment by rayusagi** [comment]
Nice, everything is working as expected now, thanks!

**Pull request merged**
