### PR TITLE
Added gym badges

### PR DESCRIPTION
**Pull request by KRDecadeZero**
Added image for every gym badges in all gen. The list of the badges is committed in main github

### CODE REVIEW

**Comment by C-Garza** [comment]
I noticed that the first badge of gen1 is still a webp file, could you change that to png? I also noticed that gen7 folder is missing.

**Comment by KRDecadeZero** [comment]
I've fixed the badge for gen1. There is no badges for gen7 since there is no gym, the closest thing there is are z crystals. Do you want me to add them as well?

**Comment by Naramsim** [comment]
Thanks! I wonder if splitting the badges by _generation_ makes sense here. I see that they are tied to a certain location, not to a generation. 

Maybe the best option would be a flat hierarchy, where all badges are inside the `/badges/` folder and they are numbered (1-58) using the ID you already provided in this [PR](https://github.com/PokeAPI/pokeapi/pull/712/files#diff-2c443a6bd75509f0519c7c2093e19aac8f1f21e6b9ef7109b2c45acabb449e82).

**Comment by KRDecadeZero** [comment]
I've put everything in the badges folder and numbered them

**Pull request merged**
