### PR TITLE
Add all Smogon sprites

### PR DESCRIPTION
**Pull request by Naramsim**
To test this PR you should extract [gen6 Smogon's sprites](https://drive.google.com/file/d/11TRnTGNciPlv55FdXO583U9Aw2bz0ypx/view) in the `/smogon/gen6` folder

Todo:

- [ ] gen7
- [ ] gen8
- [ ] forms

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @zacbullard and @C-Garza,

I made a Bash script to add all remaining Smogon sprites: https://github.com/PokeAPI/sprites/blob/smogon-sprites/scripts/renameSmogon.sh

Could you give me an initial review? 

We need to figure out how to add the forms since they have a particular name in the Smogon data.

**Comment by C-Garza** [comment]
Looks good, I'm going to play around with that file. I made it output a txt file of images skipped so it's easier to know what was missed.

I was thinking about how to handle the forms, and I was thinking of maybe using the [Smogon spreadsheet](https://docs.google.com/spreadsheets/d/1Gn0UORn-unvcbUeQhQdEBz0ADNcH49BZZqQ1dpXm9eo/edit#gid=0) to help. Each pokemon with a form starts at 1 and increments up, so maybe read the excel file and use it as a map to get the pokemon name and number.

**Comment by Naramsim** [comment]
Their form's numbering system is not aligned with ours. So we need to use some data structure to support us.

From the columns B and C of their GSheet, with VSCode I managed to create a JSON that we can use to map.

```json
{
    "650": "chespin",
    "651": "quilladin",
    "652": "chesnaught",
    "653": "fennekin",
    "654": "braixen",
    "655": "delphox",
    "656": "froakie",
    "657": "frogadier",
    "658": "greninja",
    "659": "bunnelby",
    "660": "diggersby",
    "661": "fletchling",
    "662": "fletchinder",
    "663": "talonflame",
    "664": "scatterbug",
    "665": "spewpa",
    "666_1": "vivillon-meadow",
    "666_2": "vivillon-polar",
    "666_3": "vivillon-tundra",
    "666_4": "vivillon-continental",
    "666_5": "vivillon-garden",
    "666_6": "vivillon-elegant",
    "666_7": "vivillon-icy snow",
    "666_8": "vivillon-modern",
    "666_9": "vivillon-marine",
    "666_10": "vivillon-archipelago",
    "666_11": "vivillon-high plains",
    "666_12": "vivillon-sandstorm",
    "666_13": "vivillon-river",
    "666_14": "vivillon-monsoon",
    "666_15": "vivillon-savanna",
    "666_16": "vivillon-sun",
    "666_17": "vivillon-ocean",
    "666_18": "vivillon-jungle",
    "666_19": "vivillon-fancy",
    "666_20": "vivillon-pokeball",
    "667": "litleo",
    "668m": "pyroar-male",
    "668f": "pyroar-female",
    "669_1": "flabébé-red",
    "669_2": "flabébé-yellow",
    "669_3": "flabébé-blue",
    "669_4": "flabébé-orange",
    "669_5": "flabébé-white",
    "670_1": "floette-red",
    "670_2": "floette-yellow",
    "670_3": "floette-blue",
    "670_4": "floette-orange",
    "670_5": "floette-white",
    "670_6": "floette-eternal flower",
    "671_1": "florges-red",
    "671_2": "florges-yellow",
    "671_3": "florges-blue",
    "671_4": "florges-orange",
    "671_5": "florges-white",
    "672": "skiddo",
    "673": "gogoat",
    "674": "pancham",
    "675": "pangoro",
    "676_1": "furfrou-natural",
    "677": "espurr",
    "678m": "meowstic-male",
    "678f": "meowstic-female",
    "679_2": "honedge",
    "679_1": "honedge-sheathed",
    "680_2": "doublade",
    "680_1": "doublade-sheathed",
    "681_1": "aegislash-shield",
    "681_2": "aegislash-blade",
    "682": "spritzee",
    "683": "aromatisse",
    "684": "swirlix",
    "685": "slurpuff",
    "686": "inkay",
    "687": "malamar",
    "688": "binacle",
    "689": "barbaracle",
    "690": "skrelp",
    "691": "dragalge",
    "692": "clauncher",
    "693": "clawitzer",
    "694": "helioptile",
    "695": "heliolisk",
    "696": "tyrunt",
    "697": "tyrantrum",
    "698": "amaura",
    "699": "aurorus",
    "700": "sylveon",
    "701": "hawlucha",
    "702": "dedenne",
    "703": "carbink",
    "704": "goomy",
    "705": "sliggoo",
    "706": "goodra",
    "707": "klefki",
    "708": "phantump",
    "709": "trevenant",
    "710": "pumpkaboo-average",
    "711_1": "gourgeist-average",
    "712": "bergmite",
    "713": "avalugg",
    "714": "noibat",
    "715": "noivern",
    "716_1": "xerneas",
    "716_2": "xerneas-inactive",
    "717": "yveltal",
    "718_1": "zygarde-50%",
    "718_4": "zygarde-core",
    "718_5": "zygarde-cell",
    "719_1": "diancie",
    "720_1": "hoopa-confined",
    "720_2": "hoopa-unbound",
    "721": "volcanion"
}
```

But we need further refinement, because we call pokemons differently from what they do. An example: We have `vivillon-poke-ball` but they have `vivillon-pokeball`

**Comment by C-Garza** [comment]
Yeah I was messing around with the bash script and that google sheet downloaded as a csv and managed to append the form names, but like you said, some of the form names are different. I learned a lot more about bash scripting though 😅. 

I think we're going to have to manually adjust the form names in the JSON maps you can make, I can't really see another way. Also that JSON seems to be missing `351` and `493` from what I can see.

**Comment by Naramsim** [comment]
@C-Garza I think we are working on the script simultaneously. Let's merge this PR and then you submit your changes and I start from there. Or we decide who does the job :)

The important part is to use `jq` and make the API call with `curl` to Pokeapi to determine the form ID.

In the meantime, I'll generate a single JSON map file from the 3 GSheets

**Review by C-Garza — APPROVED** [review]
The images look correct to me, and the bash file works well.

**Pull request merged**
