### PR TITLE
Fix Toxtricity Amped Form official artwork

### PR DESCRIPTION
**Pull request by alessiocelentano**

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi Alessio, thanks again for contributing.

Currently we hold 475x475 pixels images for the `official-artwork` folder. Could you reduce the image to that size? Or point us to where you've downloaded the 600x600?

**Comment by alessiocelentano** [comment]
Hi, I'm sorry but I didn't notice. I downloaded the image from [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/File:849Toxtricity-Amped.png), there are also other resolutions but not the 475x475 one.

**Comment by Naramsim** [comment]
I saw they also have 1280px images. It would be cool to understand where they got them from

**Comment by alessiocelentano** [comment]
According to the logs, it they got it from [this](https://press.pokemon.com/en/POKEMON-DAY-CELEBRATIONS-AND-A-NEW-GIGANTAMAX-POKEMON-IN-POKEMON-SWORD) page. But it's a special case, it seems that sometimes high quality artwork are released, if not they use 475x475 from the official site.

**Pull request merged**
