### PR TITLE
Add shiny sprite 10035

### PR DESCRIPTION
**Pull request by TerraNibble**
Credit to artist: Christian Murillo

### CODE REVIEW

**Comment by Naramsim** [comment]
Isn't there an official shiny sprite?

**Comment by TerraNibble** [comment]
Is it the case that Shiny Charizard Mega Y is the same sprite as standard Mega Charizard?

**Comment by Naramsim** [comment]
yeah, much better the one you provided!

**Comment by Naramsim** [comment]
Hmm, I see that for many pokemon we have the `<id>-mega.png` version and the `10xxx.png` version. I'd say we should remove all the `<id>-mega.png`, what do you think?

**Comment by TerraNibble** [comment]
Based on the file lookup in the API code [here](https://github.com/PokeAPI/pokeapi/blob/f3fd16c59edf9defab8be3c24f43cd768747199b/data/v2/build.py#L1427); the pokemon ID file pattern is preferred over the specieId + form. Therefore it should be safe to delete the formed versions where we have both.

**Comment by Naramsim** [comment]
Would you be able to do so? :)

**Comment by Naramsim** [comment]
in the meantime I merge this one

**Comment by TerraNibble** [comment]
> Would you be able to do so? :)

How do we trigger a data build of PokeApi afterwards to ensure all links are up to date at the API level?

**Comment by Naramsim** [comment]
It's automated, you just need to update the data and then we can see the result in a staging environment

**Comment by TerraNibble** [comment]
Created #155

**Pull request merged**
