### PR TITLE
Gen 9 artwork

### LINKED ISSUE #97: Add official artwork for gen 9 Pokémon
This ticket is to track the progress on adding the official artwork of Gen9 Pokémon.

### PR DESCRIPTION
**Pull request by simonorono**
Closes #97

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @simonorono, are you using the correct official IDs?

**Comment by simonorono** [comment]
@Naramsim no, I'm waiting on the ID fix on the API repo to upload the rest of the artwork.

**Comment by simonorono** [comment]
These images come directly from the [Official Pokédex](https://www.pokemon.com/us/pokedex).

Stuff to take into account when reviewing:

* There's no official artwork in the official Pokédex for Gimmighoul (Roaming form), that one was taken from the (official page for Gimmighoul)[https://scarletviolet.pokemon.com/en-us/pokemon/gimmighoul/].
* Some official artwork look like Pokémon HOME images, for example, Squawkabilly (except green). Those were added as well since they are in the official Pokédex.

**Comment by Naramsim** [comment]
Ok, I tested 3 pokemons and they seem to be alright! I'll merge

**Pull request merged**
