### PR TITLE
Added crown tundra icons

### PR DESCRIPTION
**Pull request by TimKeding**
icons were missing from latet dlc

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @TimKeding, can I ask where you took these from?

**Comment by Naramsim** [comment]
Never mind, I've seen that the size of your sprites isn't the one we are using. Our sprites are `68x56`. Can you update your pull request with the sprites taken from `pokesprite`?

https://github.com/msikma/pokesprite

**Comment by TimKeding** [comment]
Thanks for the heads up, replaced the images with the ones you requested

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Thanks a lot!

**Pull request merged**
