### PR TITLE
Added official artwork of new Pokemon!

### PR DESCRIPTION
**Pull request by DevMike123**
Adding all missing Pokemon and their forms!

### CODE REVIEW

**Comment by DevMike123** [comment]
@Naramsim @phalt I have added Unite Pokemon as requested by everyone on account of the Unite Pokemon along with the missing forms of Pokemon.

I have also added the Pokemon from 899 to 905 as they were recently added by pokemon.com but there is no data about them in the api. Could you make the effort to add the data about them and unite Pikachu.

And lastly, I couldn't find mimikyu totem busted and gumshoos totem Pokemon in the whole Internet.

**Comment by DevMike123** [comment]
> Hi @DevMike123 , thanks for the contribs! No worries about the pokemon sprites you couldn't find. 
> 
> I'll try to review the PR tomorrow!

Ok thanks

**Comment by Bindamen** [comment]
Hello, when this improvement will be merge please?

**Comment by DevMike123** [comment]
> Hello, when this improvement will be merge please?

ask @Naramsim

**Comment by C-Garza** [comment]
I'll try to take a look at this later today.

**Comment by C-Garza** [comment]
So we have the official artwork images saved as 475x475 in dimensions. Some of the images here are bigger/smaller than that. Can you resize the bigger ones to be 475x475? As for the smaller ones I'm not sure if we want to resize them bigger than what they are because they wouldn't look quite right.

**Comment by DevMike123** [comment]
> So we have the official artwork images saved as 475x475 in dimensions. Some of the images here are bigger/smaller than that. Can you resize the bigger ones to be 475x475? As for the smaller ones I'm not sure if we want to resize them bigger than what they are because they wouldn't look quite right.

Ok I will resize them!

**Comment by DevMike123** [comment]
@Naramsim where are the shiny sprites of official artwork?

**Comment by C-Garza** [comment]
I don't think we currently have any shiny sprites of official artwork in this repo. How many are there?

**Review by oguilhermelopes — APPROVED** [review]

**Comment by simonorono** [comment]
Hi @DevMike123. I just want to point out some images that are missing for Hisuian Pokémon:

10248, Basculegion, female: https://assets.pokemon.com/assets/cms2/img/pokedex/full/902_f2.png
10249, Enamorus, Therian forme: https://assets.pokemon.com/assets/cms2/img/pokedex/full/905_f2.png

**Comment by simonorono** [comment]
Hi @DevMike123, I found several images from Hisuian Pokémons that have the wrong id in the name. For example, 10237.png you have Hisuian Braviari, but 10237 is Lilligant: https://pokeapi.co/api/v2/pokemon/10237

Here's a list of all new Pokémon with their ID and a link to the official artwork:

10229, Growlithe, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/058_f2.png
10230, Arcanine, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/059_f2.png
10231, Voltorb, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/100_f2.png
10232, Electrode, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/101_f2.png
10233, Typhlosion, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/157_f2.png
10234, Qwilfish, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/211_f2.png
10235, Sneasel, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/215_f2.png
10236, Samurott, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/503_f2.png
10237, Lilligant, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/549_f2.png
10238, Zorua, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/570_f2.png
10239, Zoroark, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/571_f2.png
10240, Braviary, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/628_f2.png
10241, Sliggo, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/705_f2.png
10242, Goodra, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/706_f2.png
10243, Avalugg, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/713.png
10244, Decidueye, Hisuian form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/724_f2.png
10245, Dialga, Origin Forme: https://assets.pokemon.com/assets/cms2/img/pokedex/full/483_f2.png
10246, Palkia, Origin Forme: https://assets.pokemon.com/assets/cms2/img/pokedex/full/484_f2.png
10247, Basculin, White-striped form: https://assets.pokemon.com/assets/cms2/img/pokedex/full/550_f3.png
10248, Basculegion, female: https://assets.pokemon.com/assets/cms2/img/pokedex/full/902_f2.png

**Review by simonorono — CHANGES_REQUESTED** [review]
Some images have the wrong id. See my previous comment.

**Comment by DevMike123** [comment]
#77 The changes have been made.

**Pull request closed without merging**
