### PR TITLE
feat: Add 8th generation gifs

### PR DESCRIPTION
**Pull request by andre23arruda**
Added 8th generation game pokémons gif:
Folders:
- animated/normal
- animated/shiny

### CODE REVIEW

**Comment by DevMike123** [comment]
@andre23arruda are you still working on this pr? If not, let us know:)

**Comment by andre23arruda** [comment]
Hello.
How are you?
So, I'm not working.
To fix it, I need to change the name of all files :(


Atenciosamente,
*André Luiz Costa de Arruda*
Tel: (12) 982399873
CEP: 79370-000


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/22/22,
02:01:37 PM

**Comment by DevMike123** [comment]
@Naramsim close the pr

**Comment by Naramsim** [comment]
Hmm, maybe we can transform all the files with a script. Something along the lines of https://github.com/PokeAPI/sprites/blob/master/scripts/renameSmogon.sh

I'll convert it to a draft

**Comment by andre23arruda** [comment]
Cool!!
It can work

**Comment by DevMike123** [comment]
> Hmm, maybe we can transform all the files with a script. Something along the lines of https://github.com/PokeAPI/sprites/blob/master/scripts/renameSmogon.sh
> 
> I'll convert it to a draft

Good decision. I would like to help in this pr.

**Comment by DevMike123** [comment]
Looking for contributors :)

**Comment by FallenDeity** [comment]
this can be closed with #105

**Comment by phalt** [comment]
Good to know, thanks

**Pull request closed without merging**
