### PR TITLE
Added official pokemon.com artwork. 

### PR DESCRIPTION
**Pull request by craig-clayton**
Megas/variant forms are currently missing, as is artwork for 721.

### CODE REVIEW

**Comment by Naramsim** [comment]
Great, maybe we should rearrange a little bit the structure of the repo. Because if we are going to add other sprites we will end up having a folder full the current Pokemon sprites and full of other folder sprites.

Maybe a structure like this:
* sprites
  * pokemons
    * main-sprites
    * official-artwork
    * sugimori (maybe in future)
  * items
    * main-sprites
    * dream-world (maybe in future)

But this restructuring should be done synchronously to a sprite URL update in pokeapi repo

I think we should use this structure: @phalt @craig-clayton @sargunster @zaneadix

**Comment by craig-clayton** [comment]
Makes sense to me

**Comment by phalt** [comment]
We should definitely add a licence to this repository before we merge. I do not want to void any copyright

**Comment by Naramsim** [comment]
http://choosealicense.com/

**Comment by phalt** [comment]
Licence added.

Let's not change the currently directory as they're used by the API, we can add additional directories in the pokemon/ folder if we need to.

**Comment by Naramsim** [comment]
To not destroy things: maybe a structure like this would be better:
* root-repo
  * sprites
  * other-sprites

**Comment by craig-clayton** [comment]
Let me know and I can update accordingly and push. :)

**Comment by Naramsim** [comment]
Just put it in `other-sprites` folder

**Comment by craig-clayton** [comment]
moved official-artwork to the other-sprites directory

**Comment by Naramsim** [comment]
Merging, since it does not conflict with pokeapi

**Pull request merged**
