### PR TITLE
add hisui region sprites for pokemon home

### PR DESCRIPTION
**Pull request by matt1484**
NOTE: there is no ID for enamorus' therian form in the the API so i didnt give it a proper id number in the image. this can just be renamed later

### CODE REVIEW

**Comment by simonorono** [comment]
@matt1484 the ID for Enamorus Therian forme is 10249

https://pokeapi.co/api/v2/pokemon/10249

**Comment by matt1484** [comment]
fixed

**Comment by DevMike123** [comment]
@matt1484 many IDs are wrong!

For example:-
The id of Hisuian Sneasel is 10235.

**Comment by DevMike123** [comment]
@simonorono

**Comment by matt1484** [comment]
Basculegion is 902 https://pokeapi.co/api/v2/pokemon/902

I have hisui sneasel as 10235 correctly

**Comment by Naramsim** [comment]
@simonorono @DevMike123 I can't review this PR, if you like to do it, please go ahead and when you are positive I'll merge

**Comment by matt1484** [comment]
Added the missing mons and fixed the basculegion female

**Comment by DevMike123** [comment]
Many more IDs are incorrect.

I will review them after 10th.

**Comment by DevMike123** [comment]
> Added the missing mons and fixed the basculegion female 

Till then you can contribute to some other projects

**Comment by matt1484** [comment]
> Many more IDs are incorrect.

You could provide some useful information. Also all the IDs are correct (at least based on looking them up in PokeAPI v2 endpoints). Only thing missing is the sprites for shiny hisui sneasel (male and female) which I will fix once I find them

**Comment by DevMike123** [comment]
> > Many more IDs are incorrect.
> 
> You could provide some useful information. Also all the IDs are correct (at least based on looking them up in PokeAPI v2 endpoints). Only thing missing is the sprites for shiny hisui sneasel (male and female) which I will fix once I find them

Ok

**Comment by DevMike123** [comment]
Female - https://img.pokemondb.net/sprites/home/shiny/sneasel-hisuian-f.png

Male - https://img.pokemondb.net/sprites/home/shiny/sneasel-hisuian.png

**Comment by DevMike123** [comment]
> > Many more IDs are incorrect.
> 
> You could provide some useful information. Also all the IDs are correct (at least based on looking them up in PokeAPI v2 endpoints). Only thing missing is the sprites for shiny hisui sneasel (male and female) which I will fix once I find them

Others are correct. I have reviewed them. You add the 2 sprites mentioned above.

**Review by DevMike123 — APPROVED** [review]
Approved!

**Comment by DevMike123** [comment]
@Naramsim pr ready for merge

**Review by simonorono — APPROVED** [review]

**Pull request merged**
