### PR TITLE
order of shiny sprites from 10158 fixed also add missing sprites

### PR DESCRIPTION
**Pull request by FallenDeity**
[erros.csv](https://github.com/PokeAPI/sprites/files/10476947/erros.csv)
also fixed above missing sprites and lowered them down to the following 
[erros.csv](https://github.com/PokeAPI/sprites/files/10476951/erros.csv)

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi! I saw some images are downscaled. Is this intended? Also some others are the same size but visually lower quality

**Comment by FallenDeity** [comment]
few image sources were tougher to find especially the missing ones but i figured out something was better than nothing as for the size i didn't particularly resize them just added them as i got it but i could resize it if need be

**Comment by Naramsim** [comment]
Maybe we could only add good quality ones. I'm the opposite of your thinking sorry 😄 So I'd add only those which have the same current size and that are taken from quality sources. Is it ok with you @FallenDeity ?

**Comment by FallenDeity** [comment]
hmm alright i suppose do tell me which ones for example u want me to remove I'll also resize the images 475x475 right?

**Comment by FallenDeity** [comment]
pretty sure other than castform most of them are fine except size issues ig

**Comment by Naramsim** [comment]
yeah, I'd remove the castforms. If in the resize to bring everything to 475x475 you lose too much quality you can remove those as well

**Comment by FallenDeity** [comment]
@Naramsim think i got all the fixes u mentioned u can take a look when u are free tell me if i need to make anymore changes

**Comment by Naramsim** [comment]
THanks a lot!

**Pull request merged**
