### PR TITLE
Add Indigo Disk sprites

### PR DESCRIPTION
**Pull request by small-bytes**
Added most of the front_default Indigo Disk sprites.

~~Missing: Iron Boulder (#1022)~~

Credit/Source: [KingOfThe-X-Roads](https://www.deviantart.com/kingofthe-x-roads)

### CODE REVIEW

**Comment by FallenDeity** [comment]
probably add the shiny ones too https://www.deviantart.com/kingofthe-x-roads/art/Gen-9-Shiny-Pokemon-Sprites-WIP-937510776 also these i dont think they are present in the repo https://www.deviantart.com/kingofthe-x-roads/art/Gen-9-Back-Sprites-920309512

**Comment by small-bytes** [comment]
> probably add the shiny ones too https://www.deviantart.com/kingofthe-x-roads/art/Gen-9-Shiny-Pokemon-Sprites-WIP-937510776 also these i dont think they are present in the repo https://www.deviantart.com/kingofthe-x-roads/art/Gen-9-Back-Sprites-920309512

This is likely not the appropriate PR for back sprites, as I do not see any for Indigo Disk yet.

**Comment by Naramsim** [comment]
Do we have [KingOfThe-X-Roads](https://www.deviantart.com/kingofthe-x-roads) permission to use his sprites? Are these custom-made?

**Comment by small-bytes** [comment]
I did not reach out for permission. Was more or less following along based on #125.

**Comment by Naramsim** [comment]
Hmm, ok! I think we should ask for permission. My bad for the last pr. 

We have the permission to use Smogon sprites, but these come for that single artist on DeviantArt. Or is the artist uploading them on the Smogon forums/website?

**Comment by simonorono** [comment]
@Naramsim @small-bytes we have the special thanks to the artist in the README since commit 6aa4c1b. We seem to have gotten their permission for issue #101.

**Comment by Naramsim** [comment]
Perfect!!! I forgot about it!

**Pull request merged**
