### PR TITLE
Added Missing Pokemon

### PR DESCRIPTION
**Pull request by DevMike123**

### CODE REVIEW

**Comment by DevMike123** [comment]
@Naramsim pr ready for merge!

**Comment by simonorono** [comment]
@DevMike123 The Hisuian Avalugg image is the same as reuglar Avalugg.

This should be the image: https://assets.pokemon.com/assets/cms2/img/pokedex/full/713_f2.png

**Comment by simonorono** [comment]
@DevMike123 

1. The Hisuian Avalugg image is the same as reuglar Avalugg. This should be the image: https://assets.pokemon.com/assets/cms2/img/pokedex/full/713_f2.png
2. Enamorus Therian forme image is missing, the ID is 10249 and the image is: https://assets.pokemon.com/assets/cms2/img/pokedex/full/905_f2.png

I don't see any other issue. Thanks!

**Review by simonorono — CHANGES_REQUESTED** [review]
1. The Hisuian Avalugg image is the same as reuglar Avalugg. This should be the image: https://assets.pokemon.com/assets/cms2/img/pokedex/full/713_f2.png
2. Enamorus Therian forme image is missing, the ID is 10249 and the image is: https://assets.pokemon.com/assets/cms2/img/pokedex/full/905_f2.png

I don't see any other issue. Thanks!

**Comment by DevMike123** [comment]
> 1. The Hisuian Avalugg image is the same as reuglar Avalugg. This should be the image: https://assets.pokemon.com/assets/cms2/img/pokedex/full/713_f2.png
> 2. Enamorus Therian forme image is missing, the ID is 10249 and the image is: https://assets.pokemon.com/assets/cms2/img/pokedex/full/905_f2.png
> 
> I don't see any other issue. Thanks!

Done.

**Comment by DevMike123** [comment]
@Naramsim ready for merge.

**Comment by Naramsim** [comment]
Whoa, thanks so much for having contributed! And thanks @simonorono for reviewing!!!

**Pull request merged**
