### PR TITLE
Swap official art for male and female basculegion

### PR DESCRIPTION
**Pull request by joseph-bayer**
Closes https://github.com/PokeAPI/pokeapi/issues/764

### CODE REVIEW

**Review by C-Garza — APPROVED** [review]
Looks good to me!

**Comment by DevMike123** [comment]
LGTM!

@Naramsim ready for merge!

**Comment by C-Garza** [comment]
I went ahead and merged this since it was a simple swap.

**Comment by Naramsim** [comment]
@C-Garza , feel free to merge even heavier PR :)

**Pull request merged**
