### PR TITLE
Add smogon sprites and forms

### PR DESCRIPTION
**Pull request by Naramsim**
@C-Garza 

I've added the JSON file. I've included also the sprites in the `/smogon` folder since I flattened them and made some modifications to the names of their sprites. Now we can work together on the same files and it will be easier.

### CODE REVIEW

**Comment by C-Garza** [comment]
I'll start changing the form names in that JSON tomorrow afternoon.

**Comment by Naramsim** [comment]
Ok, so this afternoon I'll run the script across non-forms sprites.

**Comment by Naramsim** [comment]
I've added support for Forms and GMax. If you run the script it will tell you the possible errors in the JSON file and the pokemon we don't have in our API.

You can run it with 

```sh
bash renameSmogon.sh 8
```

**Comment by C-Garza** [comment]
So I ran the script and updated the [`forms.json`](https://github.com/C-Garza/sprites/blob/smogon-sprites/scripts/forms.json) so they match the API. I also output the pokemon not found in the API with the updated JSON as 3 txt files for the different gens so it's easier to see. 

Maybe you can see if `/pokemon-form` endpoint exists for the forms?

[skipped_gen6.txt](https://github.com/PokeAPI/sprites/files/6014251/skipped_gen6.txt)
[skipped_gen7.txt](https://github.com/PokeAPI/sprites/files/6014253/skipped_gen7.txt)
[skipped_gen8.txt](https://github.com/PokeAPI/sprites/files/6014254/skipped_gen8.txt)

**Comment by Naramsim** [comment]
You can commit your changes directly to this branch @C-Garza

**Comment by C-Garza** [comment]
I thought I had, but it was my fork woops 😅

**Comment by C-Garza** [comment]
@Naramsim I don't know if you've changed the bash script much, but I think if we change this line:
```sh
pokemonID=$(curl -sS "https://pokeapi.co/api/v2/pokemon/$pokemonName" | jq -r '.id' 2>/dev/null)
```
to: 
```
pokemonID=$(curl -sS "https://pokeapi.co/api/v2/pokemon-form/$pokemonName" | jq -r '.id' 2>/dev/null)
```
it should get the correct id's for the forms. I've tested this and it seems to work just fine.

**Comment by Naramsim** [comment]
> it should get the correct id's for the forms. I've tested this and it seems to work just fine.

Yeah, Initially I thought so, but then I realized that we need to save the images under the pokemon ID, not the pokemon form ID. 

`pokemonID.png` is the correct name imho. So for VenusaurGMAX the name will be 10186, as [it is now](https://pokeapi.co/api/v2/pokemon/venusaur-gmax). Does it make sense?

**Comment by C-Garza** [comment]
Oh yes, you're right. I forgot the form ID was different from the pokemon ID.

**Comment by Naramsim** [comment]
ok, later I'll try to run the script and save all the images.

**Comment by Naramsim** [comment]
Hi @C-Garza, I ran the script for gen8 and we are missing all the alcremie forms in our API.

Also, for Toxtricity, the GMax form exists only for the two forms? Or there exists also a standard Gmax pokemon?

morpeko-full-belly and morpeko-hangry are part of the so-called esthetic forms, so those two pokemons don't exist in our API, only the forms do.

Same as for zarude-dada.

We miss zacian-behemoth-blade, zamazenta-behemoth-bash, eternatus-gmax. In the API.

**Comment by C-Garza** [comment]
For Toxtricity I believe both forms can go into the same GMax form.

**Comment by Naramsim** [comment]
Hi @C-Garza,

I think we are done. We couldn't add some forms because they are only forms and don't have a corresponding pokemon, but still, we've added loads of new sprites.

I think we can start doing some reviews on the added sprites. When we are ready to merge, I'll first remove the `/smogon` folder.

**Comment by Naramsim** [comment]
I've removed the Smogon folder, otherwise, the diff is a mess.

**Comment by Naramsim** [comment]
I checked 5 pokemon and those were correct. For me it's ok.

**Comment by C-Garza** [comment]
I went through all the front facing pokemon and they looked fine to me. Nice job on the scripting @Naramsim 👍

**Pull request merged**
