### PR TITLE
[#101] Added front-default sprites for gen9

### PR DESCRIPTION
**Pull request by diduseetheocean**
Issue: #101 

- Added front_default sprites for generation 9 in pixelated style of B/W
- Changed readme to include credits for the artist [_KingOfThe-X-Roads_](https://www.deviantart.com/kingofthe-x-roads), who created these sprites

### CODE REVIEW

**Comment by diduseetheocean** [comment]
@Naramsim 
For number 964, i included the hero-form of palafin. Maybe this isn't correct and it should be the zero-form.

**Comment by diduseetheocean** [comment]
@Naramsim
The sprites are currently not properly aligned inside the 96x96 canvas (to much left, right etc.) I will fix this.
- [ ] Fixed

**Comment by FallenDeity** [comment]
[cut.zip](https://github.com/PokeAPI/sprites/files/10582107/cut.zip)
I have centred and sized the images appropriately here you can use them also for ones which u havent yet add like tatsugiri and u made a mistake with palafin kindly refer to official artwork of sprites when adding them I have already added those before in correct order

**Comment by diduseetheocean** [comment]
Added correct form of palafin for number 964.

@FallenDeity 
I will not add the shiny ones here. In this PR i wanted only to add the front_default sprites.

**Comment by FallenDeity** [comment]
> Added correct form of palafin for number 964.
> 
> @FallenDeity I will not add the shiny ones here. In this PR i wanted only to add the front_default sprites.

its not just those like lechonk iirc female form has id in around 10254 so some mons are misplaced those need a fix

**Comment by diduseetheocean** [comment]
@FallenDeity 
Thx for your hint. I looked into your artwork PR and added/changed the sprites accordingly to match your structure.
Except i added the lechonk-female also into the female folder.
Plz have a look.

**Comment by FallenDeity** [comment]
seems fine now main reason for the specific ids is to match the api data otherwise its gonna show up as null also if u have some time do consider adding the back defaults/shiny of few hiusian and gmax pokemon they seem to be missing

**Comment by diduseetheocean** [comment]
> seems fine now main reason for the specific ids is to match the api data otherwise its gonna show up as null also if u have some time do consider adding the back defaults/shiny of few hiusian and gmax pokemon they seem to be missing

This could be done in another issue. Than could this PR be merged and closed.

**Comment by diduseetheocean** [comment]
@Naramsim 
Applied all changes. Rdy for review.

**Review by DevMike123 — APPROVED** [review]
Thanks for contributing

**Pull request merged**
