### PR TITLE
add showdown type sprites

### PR DESCRIPTION
**Pull request by FallenDeity**
Contains almost all showdown/3d model sprites that I could find with exceptions of not yet released gen 9 mons and a few pokemon backwards sprites 
- pikcachu libre back sprite normal and shiny
- venusaur gmax
- blastoise gmax
- urshifu gmax both forms
- gen 8 starter gmax forms
iirc those should be about it.
Another query i have would be about the different form variations of pokemons like unown, arceus, alcremie, silvally etc are those to be added or is there a slot for them.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, the diff is too large and github cannot render it. Can you embed some images here so we see what they look like?

**Comment by Naramsim** [comment]
for unown, arceus, alcremie, silvally, you can check out if there's multiple pokemon (`id`>10000) or if there's `pokemon-form`s for them.

**Comment by FallenDeity** [comment]
images are xy style 3d models used in showdown refrences can be found here
https://play.pokemonshowdown.com/sprites/ 
ani and ani-back shiny etc
@Naramsim 
also the form do exist in pokeapi Pokemon endpoint under forms category should I add them like id-form.gif in the folders also all the sprites are in a showdown folder with same file structure as the gen 5 type default sprites

**Comment by Naramsim** [comment]
Ok, perfect, are those XY format or ultra sun ultra moon? I see that the two kinds are pretty similar, if not the same. 

Depending on which one we think they belong to, we can put them in the `appropriate-folder/animated`. PS: all of those images come from ROMs? Or some of them have been created by the Smogon community?

**Comment by FallenDeity** [comment]
also its 3ds style sprite that's why it's similar to xy and sm

**Comment by FallenDeity** [comment]
@Naramsim any updates?

**Comment by Naramsim** [comment]
Hi @FallenDeity , yes, I can't review this PR as it is now, it's too big and even checking it out locally I'm having an hard time. 

Can we create a smaller one, easier to review?

I'd start from the additions: 

- pikcachu libre back sprite normal and shiny
- venusaur gmax
- blastoise gmax
- urshifu gmax both forms
- gen 8 starter gmax forms

Leaving out all showdown/3d?

**Comment by FallenDeity** [comment]
> Hi @FallenDeity , yes, I can't review this PR as it is now, it's too big and even checking it out locally I'm having an hard time.
> 
> Can we create a smaller one, easier to review?
> 
> I'd start from the additions:
> 
> * pikcachu libre back sprite normal and shiny
> * venusaur gmax
> * blastoise gmax
> * urshifu gmax both forms
> * gen 8 starter gmax forms
> 
> Leaving out all showdown/3d?

the ones u mentioned like pikachu libre venusaur etc their 3ds sprites are unavailable if u want I can make updates one by one like front-default shiny and so on but it should still be easy to view changes right just clone it locally and browse with file browser if u wanna check images then just keep the thumbnail setting on. splitting this seems more work as of now.

**Comment by Naramsim** [comment]
> the ones u mentioned like pikachu libre venusaur etc their 3ds sprites are unavailable

I don't understand then, why in the first message you wrote those names?

**Comment by FallenDeity** [comment]
> > the ones u mentioned like pikachu libre venusaur etc their 3ds sprites are unavailable
> 
> I don't understand then, why in the first message you wrote those names?

i wrote those as a record so that the missing gifs can be added later when its available cause if only I have it in a excel file locally or something I might accidentally delete it also if the missing ones are compiled in one place properly its easier for others to contribute as well.

**Comment by Naramsim** [comment]
Ahhh, ok, it wasn't clear. Ok. 

So the changes of this PR are just the addition of the images under `/smogon`?

**Comment by FallenDeity** [comment]
> Ahhh, ok, it wasn't clear. Ok.
> 
> So the changes of this PR are just the addition of the images under `/pokemon/showdown`?

yes. Also presumably changes need to be made in the api as well to include another showdown field for pokemon endpoint

**Comment by FallenDeity** [comment]
any updates on this pr or should i add another commit including the forms of showdown pokemon like arceus silvally etc

**Comment by Naramsim** [comment]
Hey @FallenDeity sorry I haven't come back. Right now I don't really have time. I'm traveling and have no spare time for Github. I'll take a deeper look in the next weeks. Sorryyyy

**Comment by FallenDeity** [comment]
@Naramsim leave a ping or message when you do take a look though 🥺

**Comment by FallenDeity** [comment]
> any updates on this pr or should i add another commit including the forms of showdown pokemon like arceus silvally etc


added forms of pokemons as well as mentioned above also it would be good to receive some updates about this pr cause i personally feel this would be a pretty cool addition to the api enabling many devs to make animated games and some cool stuff

**Comment by Naramsim** [comment]
I'll try to look at it on Tuesday maybe 😆

Thanks so much for it!

**Comment by Naramsim** [comment]
I merged! I moved everything to the `other` folder. TY

**Comment by FallenDeity** [comment]
aight cool 😎

**Pull request merged**
