### PR TITLE
Missing sprites

### PR DESCRIPTION
**Pull request by DevMike123**

### CODE REVIEW

**Comment by DevMike123** [comment]
@Naramsim pr ready for merge

**Comment by Naramsim** [comment]
Thanks!

**Comment by joseph-bayer** [comment]
Hey @DevMike123 and @Naramsim!

This pr provided a huge amount of missing art - when do the changes get reflected on the API?

I'm asking because I'm not sure if it's an automatic process to update the API or something that needs to be done manually. If it has to be done manually, I'd love to help!

Thanks,

-Joe

**Comment by DevMike123** [comment]
> Hey @DevMike123 and @Naramsim!
> 
> This pr provided a huge amount of missing art - when do the changes get reflected on the API?
> 
> I'm asking because I'm not sure if it's an automatic process to update the API or something that needs to be done manually. If it has to be done manually, I'd love to help!
> 
> Thanks,
> 
> -Joe

It's automatic.

**Comment by joseph-bayer** [comment]
@DevMike123 - cool! Does a pipeline need to be ran? I don’t see these images when calling the current API. For example, the payload for Eternal Floette doesn’t have the official art url populated: https://pokeapi.co/api/v2/pokemon/floette-eternal

**Comment by C-Garza** [comment]
The sprites repo lives as a submodule in pokeapi here [https://github.com/PokeAPI/pokeapi/tree/master/data/v2](https://github.com/PokeAPI/pokeapi/tree/master/data/v2). The commit it's pointing to probably has to be updated.

**Comment by joseph-bayer** [comment]
> The sprites repo lives as a submodule in pokeapi here https://github.com/PokeAPI/pokeapi/tree/master/data/v2. The commit it's pointing to probably has to be updated.

Ah that makes sense! If the timing is right to update that, I can create a pull request pointing to the newest commit in the sprites repo (preferably after [this pull request](https://github.com/PokeAPI/sprites/pull/91) is  merged).

**Comment by DevMike123** [comment]
> > The sprites repo lives as a submodule in pokeapi here https://github.com/PokeAPI/pokeapi/tree/master/data/v2. The commit it's pointing to probably has to be updated.
> 
> Ah that makes sense! If the timing is right to update that, I can create a pull request pointing to the newest commit in the sprites repo (preferably after [this pull request](https://github.com/PokeAPI/sprites/pull/91) is  merged).

With pleasure

**Pull request merged**
