### PR TITLE
correct: Use clear sprites instead of blurry for gen 9 shinies

### PR DESCRIPTION
**Pull request by yassenshopov**
For the vast majority of Gen 9 pokemon (with the exception of Iron Crown, Hydrapple, Iron Boulder, and a few others) a blurry version of the original pixelated shiny sprite has been used, and they are usually also displaced r resized improperly in relation to the non-shiny respective sprites.

This PR replaces the blurry images with clear versions of them, and you will be able to see the difference in the PR diffs. Also, a shiny sprite for Pecharunt was added too.

You can see how the previously blurry sprites looked off on one of my personal projects, [Pokemon Palette](https://pokemnpalette.com), which extracts colors from Pokemon sprites.

### CODE REVIEW

**Comment by yassenshopov** [comment]
@FallenDeity and @Naramsim, what do you think?

**Comment by Naramsim** [comment]
> @FallenDeity and @Naramsim, what do you think?

Hi, I saw the pr on mobile, everything seems great. Though, I cannot see the diffs on mobile. I will check them in the next days. 

Thanks so much for the contribution!!

**Comment by yassenshopov** [comment]
@Naramsim , just a reminder, in case this got lost in your inbox 😀

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Great job! They all look fantastic!!

**Pull request merged**
