### PR TITLE
Victorb999 gen 8

### PR DESCRIPTION
**Pull request by Victorb999**
Made some imgs for sprites of generation 8.

### CODE REVIEW

**Comment by magical** [comment]
*squints* is that the Sugimori artwork?

**Comment by Victorb999** [comment]
I think so, i pick from _serebii_ and resize in 128x 128.
https://serebii.net/art/th/810.png

**Comment by Naramsim** [comment]
Thanks for the contribution @Victorb999. I've seen that in our _main_ sprites folder there is a big mess. We've used the Black/White format up till the pokemon 721. Then for gen 7, we used a different format, I don't know the name. I think that adding the Sugimori artwork here in this folder is not the best thing. 

I would add those images (in 475x475 format) to the folder: /sprites/pokemon/other/official-artwork.

**Comment by Victorb999** [comment]
I understand, when saw the folder i didn't realize a pattern to follow. All generations sprites look different, in size and in art, but it's normal because they are made for different consoles with different technologies in different years. Maybe in future would be nice make a default type. 
When I made this images I was looking for art of the game but i didn't find in a good resolution. Maybe I will make a better search and open a new PR with then.
This api help me so much in my VueJs studies , it's a pleasure try to help.

**Comment by Naramsim** [comment]
Well, you can re-open just now another PR and adding your files to the above mentioned folder :)

**Comment by Naramsim** [comment]
About standardizing the root folder, it's a thing we need to do.

**Comment by Victorb999** [comment]
https://www.smogon.com/forums/threads/sword-shield-sprite-project.3647722/
https://docs.google.com/spreadsheets/d/1acgzAjh0dnFRQnjZu8kSjS177rKCzpFfEHRLtwuuXRU/edit?usp=sharing
Do you think sprites on this link is the correct?

**Comment by Naramsim** [comment]
Yeah! I think the art is compatible with the one we offer! We could add those in our root folder.

**Comment by Victorb999** [comment]
Nice!! I'm working in this, i think we should replace some of gen 7 which is looking very different. For exemple Zeraora.

**Pull request closed without merging**
