### PR TITLE
Sprites Gen 8

### PR DESCRIPTION
**Pull request by Victorb999**
Sprites Gen 8, pick from [Smogon](https://www.smogon.com/forums/). Update some gen 7.

### CODE REVIEW

**Comment by phalt** [comment]
I that 3 sprite files have changed, quite a bit (from a 3DS model to what looks like sprite work) - is that normal? They're ultra beast and mythical so I'm guessing it's because they were non-official before.

**Comment by Naramsim** [comment]
@phalt, if you're referring to 805, 806, 807 it's normal. The sprites @Victorb999 used are in line with all the other we are currently serving. Probably when we added 805, 806 and 807 by ourself we picked the wrong art.

**Comment by Naramsim** [comment]
Anyway, I noted that also those sprites (gen-8 that @Victorb999 added) are not official. Those are the sprites that @Zarel mentioned to us! (https://github.com/PokeAPI/sprites/pull/18#issuecomment-669768826)

If we want to use them we need to quote that those are coming from Smogon and we also have to reference the spriter 😄 

I'm in favor of adding them and giving all the credits

**Comment by Victorb999** [comment]
> I see that 3 sprite files have changed, quite a bit (from a 3DS model to what looks like sprite work) - is that normal? They're ultra beast and mythical so I'm guessing it's because they were non-official before.

They look little different of others for me, take a look.
image
image

gen I  from exemple
image

> Anyway, I noted that also those sprites (gen-8 that @Victorb999 added) are not official. Those are the sprites that @Zarel mentioned to us! ([#18 (comment)](https://github.com/PokeAPI/sprites/pull/18#issuecomment-669768826))
> 
> If we want to use them we need to quote that those are coming from Smogon and we also have to reference the spriter 😄
> 
> I'm in favor of adding them and giving all the credits

I think it's a better thing to do. 😁

**Comment by Naramsim** [comment]
Ok, @Victorb999 I'm merging this PR and later I'll add the reference to Smogon and the spriters.

I also noted that our gen-7 pokemons are of a different kind. Smogon created sprites that look like B/W here:

https://www.smogon.com/forums/threads/sun-moon-sprite-project.3577711/
https://docs.google.com/spreadsheets/d/1FMcHbSKEWZc7v2Ur4cyJjT_NhO0gqXyU9kDhsOQhlBQ/edit#gid=0

We should replace ours with theirs and also reference those ones.

**Comment by Victorb999** [comment]
> Ok, @Victorb999 I'm merging this PR and later I'll add the reference to Smogon and the spriters.
> 
> I also noted that our gen-7 pokemons are of a different kind. Smogon created sprites that look like B/W here:
> 
> https://www.smogon.com/forums/threads/sun-moon-sprite-project.3577711/
> https://docs.google.com/spreadsheets/d/1FMcHbSKEWZc7v2Ur4cyJjT_NhO0gqXyU9kDhsOQhlBQ/edit#gid=0
> 
> We should replace ours with theirs and also reference those ones.

I'll do it, and make a new PR with it.

**Comment by Naramsim** [comment]
Thanks a lot! 

PS: be sure to participate in the upcoming Hacktoberfest! 

https://hacktoberfest.digitalocean.com/

**Pull request merged**
