### PR TITLE
Added Badge

### PR DESCRIPTION
**Pull request by DevMike123**

### CODE REVIEW

**Comment by DevMike123** [comment]
@Naramsim pr ready for merge

**Comment by Naramsim** [comment]
Same here

**Comment by Naramsim** [comment]
This branch cannot be rebased due to conflicts. maybe it's better if you start from a clean `master`

**Comment by DevMike123** [comment]
> This branch cannot be rebased due to conflicts. maybe it's better if you start from a clean `master`

Ok

**Pull request closed without merging**
